import React from 'react';
import { XIcon } from './Icons';

interface LegalModalProps {
  isOpen: boolean;
  type: 'terms' | 'privacy' | null;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, type, onClose }) => {
  if (!isOpen || !type) return null;

  const title = type === 'terms' ? 'Terms of Service' : 'Privacy Policy';
  
  const content = type === 'terms' ? (
    <>
      <div className="space-y-4">
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">1. Acceptance of Terms</h4>
          <p>By accessing and using Vitalis AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">2. Medical Disclaimer</h4>
          <p className="text-rose-600 dark:text-rose-400 font-medium">Vitalis AI is an experimental analysis tool and DOES NOT provide medical advice, diagnosis, or treatment.</p>
          <p>The content generated by this AI is for informational purposes only. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">3. User Responsibility</h4>
          <p>You are responsible for the data you upload. Do not upload sensitive Personal Identifiable Information (PII) of others without consent.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">4. Availability</h4>
          <p>We do not guarantee continuous, uninterrupted, or secure access to our services. We reserve the right to modify or discontinue the service at any time.</p>
        </section>
      </div>
    </>
  ) : (
    <>
      <div className="space-y-4">
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">1. Data Collection</h4>
          <p>We collect the images and text you upload solely for the purpose of analyzing them during your session. We use the Google Gemini API to process this data.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">2. Data Storage</h4>
          <p>If you use the app as a guest, your reports are stored locally in your browser (LocalStorage) and are not sent to our permanent database.</p>
          <p>If you sign in, your reports are stored securely in our database to allow you to access them from the Dashboard.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">3. Third-Party Services</h4>
          <p>We utilize Google Cloud Vertex AI / Gemini API for data processing. Please refer to Google's Privacy Policy regarding how they handle data processing.</p>
        </section>
        <section>
          <h4 className="font-bold text-slate-800 dark:text-white mb-1">4. Your Rights</h4>
          <p>You can delete your saved reports at any time via the Dashboard. You can also clear your browser data to remove local guest reports.</p>
        </section>
      </div>
    </>
  );

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm animate-in fade-in duration-200" onClick={onClose}>
      <div 
        className="bg-white dark:bg-slate-800 rounded-2xl shadow-xl max-w-lg w-full max-h-[85vh] flex flex-col overflow-hidden animate-in slide-in-from-bottom-4 zoom-in-95 duration-200"
        onClick={e => e.stopPropagation()}
      >
         <div className="p-5 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center bg-slate-50/50 dark:bg-slate-800">
            <h3 className="font-bold text-xl text-slate-800 dark:text-white font-serif">{title}</h3>
            <button 
              onClick={onClose} 
              className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-full transition-colors text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            >
              <XIcon className="w-5 h-5" />
            </button>
         </div>
         <div className="p-6 overflow-y-auto custom-scrollbar text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
           {content}
         </div>
         <div className="p-4 border-t border-slate-100 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 flex justify-end">
           <button 
             onClick={onClose} 
             className="px-5 py-2.5 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-xl font-medium text-sm hover:bg-slate-800 dark:hover:bg-slate-200 transition-colors shadow-sm"
           >
             Close
           </button>
         </div>
      </div>
    </div>
  );
};
